FROM maven:alpine

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN adb shell am start -n "epitech.eu.mobile/epitech.eu.mobile.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER]
