version: "3"

services:
  server:
    image: strapi/strapi
    container_name: server
    restart: unless-stopped
    env_file: .env
    networks:
      - strapi-app-network
    volumes:
      - .:/srv/app:z
    ports:
      - "8080:8080"

networks:
  strapi-app-network:
    driver: bridge

